package com.saber.spring.camel.test1.dto.wsdl.basicinformation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-26T02:13:12.911+04:30
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "BasicInformationQueryService",
                  wsdlLocation = "file:/C:/Users/SABER/AppData/Local/Temp/tempdir4910992496533008133.tmp/BasicInformationQueryService_1.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class BasicInformationQueryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "BasicInformationQueryService");
    public final static QName WSHttpBindingIBasicInformationQueryService = new QName("http://tempuri.org/", "WSHttpBinding_IBasicInformationQueryService");
    public final static QName SSLCustomBindingIBasicInformationQueryService = new QName("http://tempuri.org/", "SSL_CustomBinding_IBasicInformationQueryService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/SABER/AppData/Local/Temp/tempdir4910992496533008133.tmp/BasicInformationQueryService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BasicInformationQueryService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/SABER/AppData/Local/Temp/tempdir4910992496533008133.tmp/BasicInformationQueryService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BasicInformationQueryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BasicInformationQueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicInformationQueryService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BasicInformationQueryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BasicInformationQueryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BasicInformationQueryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IBasicInformationQueryService
     */
    @WebEndpoint(name = "WSHttpBinding_IBasicInformationQueryService")
    public IBasicInformationQueryService getWSHttpBindingIBasicInformationQueryService() {
        return super.getPort(WSHttpBindingIBasicInformationQueryService, IBasicInformationQueryService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBasicInformationQueryService
     */
    @WebEndpoint(name = "WSHttpBinding_IBasicInformationQueryService")
    public IBasicInformationQueryService getWSHttpBindingIBasicInformationQueryService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIBasicInformationQueryService, IBasicInformationQueryService.class, features);
    }


    /**
     *
     * @return
     *     returns IBasicInformationQueryService
     */
    @WebEndpoint(name = "SSL_CustomBinding_IBasicInformationQueryService")
    public IBasicInformationQueryService getSSLCustomBindingIBasicInformationQueryService() {
        return super.getPort(SSLCustomBindingIBasicInformationQueryService, IBasicInformationQueryService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBasicInformationQueryService
     */
    @WebEndpoint(name = "SSL_CustomBinding_IBasicInformationQueryService")
    public IBasicInformationQueryService getSSLCustomBindingIBasicInformationQueryService(WebServiceFeature... features) {
        return super.getPort(SSLCustomBindingIBasicInformationQueryService, IBasicInformationQueryService.class, features);
    }

}
