
package com.saber.spring.camel.test1.dto.wsdl.basicinformation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-26T02:13:12.722+04:30
 * Generated source version: 3.4.4
 *
 */
public final class IBasicInformationQueryService_WSHttpBindingIBasicInformationQueryService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "BasicInformationQueryService");

    private IBasicInformationQueryService_WSHttpBindingIBasicInformationQueryService_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BasicInformationQueryService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BasicInformationQueryService ss = new BasicInformationQueryService(wsdlURL, SERVICE_NAME);
        IBasicInformationQueryService port = ss.getWSHttpBindingIBasicInformationQueryService();

        {
        System.out.println("Invoking getOrganizationTypes...");
        ArrayOfBasicInformation _getOrganizationTypes__return = port.getOrganizationTypes();
        System.out.println("getOrganizationTypes.result=" + _getOrganizationTypes__return);


        }
        {
        System.out.println("Invoking getAddressTypes...");
        ArrayOfBasicInformation _getAddressTypes__return = port.getAddressTypes();
        System.out.println("getAddressTypes.result=" + _getAddressTypes__return);


        }
        {
        System.out.println("Invoking getDegrees...");
        ArrayOfBasicInformation _getDegrees__return = port.getDegrees();
        System.out.println("getDegrees.result=" + _getDegrees__return);


        }
        {
        System.out.println("Invoking getLanguageSkillLevels...");
        ArrayOfBasicInformation _getLanguageSkillLevels__return = port.getLanguageSkillLevels();
        System.out.println("getLanguageSkillLevels.result=" + _getLanguageSkillLevels__return);


        }
        {
        System.out.println("Invoking getLanguages...");
        ArrayOfBasicInformation _getLanguages__return = port.getLanguages();
        System.out.println("getLanguages.result=" + _getLanguages__return);


        }
        {
        System.out.println("Invoking getActivityTypes...");
        ArrayOfBasicInformation _getActivityTypes__return = port.getActivityTypes();
        System.out.println("getActivityTypes.result=" + _getActivityTypes__return);


        }
        {
        System.out.println("Invoking getOwnerTypes...");
        ArrayOfBasicInformation _getOwnerTypes__return = port.getOwnerTypes();
        System.out.println("getOwnerTypes.result=" + _getOwnerTypes__return);


        }
        {
        System.out.println("Invoking getFields...");
        ArrayOfBasicInformation _getFields__return = port.getFields();
        System.out.println("getFields.result=" + _getFields__return);


        }
        {
        System.out.println("Invoking getCountries...");
        ArrayOfBasicInformation _getCountries__return = port.getCountries();
        System.out.println("getCountries.result=" + _getCountries__return);


        }
        {
        System.out.println("Invoking getMaritalStatuses...");
        ArrayOfBasicInformation _getMaritalStatuses__return = port.getMaritalStatuses();
        System.out.println("getMaritalStatuses.result=" + _getMaritalStatuses__return);


        }
        {
        System.out.println("Invoking getGenders...");
        ArrayOfBasicInformation _getGenders__return = port.getGenders();
        System.out.println("getGenders.result=" + _getGenders__return);


        }
        {
        System.out.println("Invoking getIdentificationDocumentTypes...");
        ArrayOfBasicInformation _getIdentificationDocumentTypes__return = port.getIdentificationDocumentTypes();
        System.out.println("getIdentificationDocumentTypes.result=" + _getIdentificationDocumentTypes__return);


        }
        {
        System.out.println("Invoking getQuestions...");
        ArrayOfBasicInformation _getQuestions__return = port.getQuestions();
        System.out.println("getQuestions.result=" + _getQuestions__return);


        }
        {
        System.out.println("Invoking getPoliticalRepresentationTypes...");
        ArrayOfBasicInformation _getPoliticalRepresentationTypes__return = port.getPoliticalRepresentationTypes();
        System.out.println("getPoliticalRepresentationTypes.result=" + _getPoliticalRepresentationTypes__return);


        }
        {
        System.out.println("Invoking getResponsesResponses...");
        ArrayOfBasicInformation _getResponsesResponses__return = port.getResponsesResponses();
        System.out.println("getResponsesResponses.result=" + _getResponsesResponses__return);


        }

        System.exit(0);
    }

}
