
package com.saber.spring.camel.test1.dto.wsdl.basicinformation;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-26T02:13:12.892+04:30
 * Generated source version: 3.4.4
 *
 */

public class IBasicInformationQueryService_WSHttpBindingIBasicInformationQueryService_Server{

    protected IBasicInformationQueryService_WSHttpBindingIBasicInformationQueryService_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new WSHttpBinding_IBasicInformationQueryServiceImpl();
        String address = "http://fida-soap-svc/BasicInformationQueryService/ws";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new IBasicInformationQueryService_WSHttpBindingIBasicInformationQueryService_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
