package com.saber.spring.camel.test1.dto.wsdl.basicinformation;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-26T02:13:12.876+04:30
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IBasicInformationQueryService")
@XmlSeeAlso({ObjectFactory.class})
public interface IBasicInformationQueryService {

    @WebMethod(operationName = "GetOrganizationTypes", action = "http://tempuri.org/IBasicInformationQueryService/GetOrganizationTypes")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetOrganizationTypes", output = "http://tempuri.org/IBasicInformationQueryService/GetOrganizationTypesResponse")
    @RequestWrapper(localName = "GetOrganizationTypes", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetOrganizationTypes")
    @ResponseWrapper(localName = "GetOrganizationTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetOrganizationTypesResponse")
    @WebResult(name = "GetOrganizationTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getOrganizationTypes()
;

    @WebMethod(operationName = "GetAddressTypes", action = "http://tempuri.org/IBasicInformationQueryService/GetAddressTypes")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetAddressTypes", output = "http://tempuri.org/IBasicInformationQueryService/GetAddressTypesResponse")
    @RequestWrapper(localName = "GetAddressTypes", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetAddressTypes")
    @ResponseWrapper(localName = "GetAddressTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetAddressTypesResponse")
    @WebResult(name = "GetAddressTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getAddressTypes()
;

    @WebMethod(operationName = "GetDegrees", action = "http://tempuri.org/IBasicInformationQueryService/GetDegrees")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetDegrees", output = "http://tempuri.org/IBasicInformationQueryService/GetDegreesResponse")
    @RequestWrapper(localName = "GetDegrees", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetDegrees")
    @ResponseWrapper(localName = "GetDegreesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetDegreesResponse")
    @WebResult(name = "GetDegreesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getDegrees()
;

    @WebMethod(operationName = "GetLanguageSkillLevels", action = "http://tempuri.org/IBasicInformationQueryService/GetLanguageSkillLevels")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetLanguageSkillLevels", output = "http://tempuri.org/IBasicInformationQueryService/GetLanguageSkillLevelsResponse")
    @RequestWrapper(localName = "GetLanguageSkillLevels", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetLanguageSkillLevels")
    @ResponseWrapper(localName = "GetLanguageSkillLevelsResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetLanguageSkillLevelsResponse")
    @WebResult(name = "GetLanguageSkillLevelsResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getLanguageSkillLevels()
;

    @WebMethod(operationName = "GetLanguages", action = "http://tempuri.org/IBasicInformationQueryService/GetLanguages")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetLanguages", output = "http://tempuri.org/IBasicInformationQueryService/GetLanguagesResponse")
    @RequestWrapper(localName = "GetLanguages", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetLanguages")
    @ResponseWrapper(localName = "GetLanguagesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetLanguagesResponse")
    @WebResult(name = "GetLanguagesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getLanguages()
;

    @WebMethod(operationName = "GetActivityTypes", action = "http://tempuri.org/IBasicInformationQueryService/GetActivityTypes")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetActivityTypes", output = "http://tempuri.org/IBasicInformationQueryService/GetActivityTypesResponse")
    @RequestWrapper(localName = "GetActivityTypes", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetActivityTypes")
    @ResponseWrapper(localName = "GetActivityTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetActivityTypesResponse")
    @WebResult(name = "GetActivityTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getActivityTypes()
;

    @WebMethod(operationName = "GetOwnerTypes", action = "http://tempuri.org/IBasicInformationQueryService/GetOwnerTypes")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetOwnerTypes", output = "http://tempuri.org/IBasicInformationQueryService/GetOwnerTypesResponse")
    @RequestWrapper(localName = "GetOwnerTypes", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetOwnerTypes")
    @ResponseWrapper(localName = "GetOwnerTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetOwnerTypesResponse")
    @WebResult(name = "GetOwnerTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getOwnerTypes()
;

    @WebMethod(operationName = "GetFields", action = "http://tempuri.org/IBasicInformationQueryService/GetFields")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetFields", output = "http://tempuri.org/IBasicInformationQueryService/GetFieldsResponse")
    @RequestWrapper(localName = "GetFields", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetFields")
    @ResponseWrapper(localName = "GetFieldsResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetFieldsResponse")
    @WebResult(name = "GetFieldsResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getFields()
;

    @WebMethod(operationName = "GetCountries", action = "http://tempuri.org/IBasicInformationQueryService/GetCountries")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetCountries", output = "http://tempuri.org/IBasicInformationQueryService/GetCountriesResponse")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetCountriesResponse")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getCountries()
;

    @WebMethod(operationName = "GetMaritalStatuses", action = "http://tempuri.org/IBasicInformationQueryService/GetMaritalStatuses")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetMaritalStatuses", output = "http://tempuri.org/IBasicInformationQueryService/GetMaritalStatusesResponse")
    @RequestWrapper(localName = "GetMaritalStatuses", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetMaritalStatuses")
    @ResponseWrapper(localName = "GetMaritalStatusesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetMaritalStatusesResponse")
    @WebResult(name = "GetMaritalStatusesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getMaritalStatuses()
;

    @WebMethod(operationName = "GetGenders", action = "http://tempuri.org/IBasicInformationQueryService/GetGenders")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetGenders", output = "http://tempuri.org/IBasicInformationQueryService/GetGendersResponse")
    @RequestWrapper(localName = "GetGenders", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetGenders")
    @ResponseWrapper(localName = "GetGendersResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetGendersResponse")
    @WebResult(name = "GetGendersResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getGenders()
;

    @WebMethod(operationName = "GetIdentificationDocumentTypes", action = "http://tempuri.org/IBasicInformationQueryService/GetIdentificationDocumentTypes")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetIdentificationDocumentTypes", output = "http://tempuri.org/IBasicInformationQueryService/GetIdentificationDocumentTypesResponse")
    @RequestWrapper(localName = "GetIdentificationDocumentTypes", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetIdentificationDocumentTypes")
    @ResponseWrapper(localName = "GetIdentificationDocumentTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetIdentificationDocumentTypesResponse")
    @WebResult(name = "GetIdentificationDocumentTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getIdentificationDocumentTypes()
;

    @WebMethod(operationName = "GetQuestions", action = "http://tempuri.org/IBasicInformationQueryService/GetQuestions")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetQuestions", output = "http://tempuri.org/IBasicInformationQueryService/GetQuestionsResponse")
    @RequestWrapper(localName = "GetQuestions", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetQuestions")
    @ResponseWrapper(localName = "GetQuestionsResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetQuestionsResponse")
    @WebResult(name = "GetQuestionsResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getQuestions()
;

    @WebMethod(operationName = "GetPoliticalRepresentationTypes", action = "http://tempuri.org/IBasicInformationQueryService/GetPoliticalRepresentationTypes")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetPoliticalRepresentationTypes", output = "http://tempuri.org/IBasicInformationQueryService/GetPoliticalRepresentationTypesResponse")
    @RequestWrapper(localName = "GetPoliticalRepresentationTypes", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetPoliticalRepresentationTypes")
    @ResponseWrapper(localName = "GetPoliticalRepresentationTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetPoliticalRepresentationTypesResponse")
    @WebResult(name = "GetPoliticalRepresentationTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getPoliticalRepresentationTypes()
;

    @WebMethod(operationName = "GetResponsesResponses", action = "http://tempuri.org/IBasicInformationQueryService/GetResponsesResponses")
    @Action(input = "http://tempuri.org/IBasicInformationQueryService/GetResponsesResponses", output = "http://tempuri.org/IBasicInformationQueryService/GetResponsesResponsesResponse")
    @RequestWrapper(localName = "GetResponsesResponses", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetResponsesResponses")
    @ResponseWrapper(localName = "GetResponsesResponsesResponse", targetNamespace = "http://tempuri.org/", className = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.GetResponsesResponsesResponse")
    @WebResult(name = "GetResponsesResponsesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfBasicInformation getResponsesResponses()
;
}
