
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.saber.spring.camel.test1.dto.wsdl.basicinformation;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-26T02:13:12.856+04:30
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "BasicInformationQueryService",
                      portName = "SSL_CustomBinding_IBasicInformationQueryService",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "file:/C:/Users/SABER/AppData/Local/Temp/tempdir4910992496533008133.tmp/BasicInformationQueryService_1.wsdl",
                      endpointInterface = "com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService")

public class SSL_CustomBinding_IBasicInformationQueryServiceImpl implements IBasicInformationQueryService {

    private static final Logger LOG = Logger.getLogger(SSL_CustomBinding_IBasicInformationQueryServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getOrganizationTypes()*
     */
    public ArrayOfBasicInformation getOrganizationTypes() {
        LOG.info("Executing operation getOrganizationTypes");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getAddressTypes()*
     */
    public ArrayOfBasicInformation getAddressTypes() {
        LOG.info("Executing operation getAddressTypes");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getDegrees()*
     */
    public ArrayOfBasicInformation getDegrees() {
        LOG.info("Executing operation getDegrees");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getLanguageSkillLevels()*
     */
    public ArrayOfBasicInformation getLanguageSkillLevels() {
        LOG.info("Executing operation getLanguageSkillLevels");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getLanguages()*
     */
    public ArrayOfBasicInformation getLanguages() {
        LOG.info("Executing operation getLanguages");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getActivityTypes()*
     */
    public ArrayOfBasicInformation getActivityTypes() {
        LOG.info("Executing operation getActivityTypes");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getOwnerTypes()*
     */
    public ArrayOfBasicInformation getOwnerTypes() {
        LOG.info("Executing operation getOwnerTypes");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getFields()*
     */
    public ArrayOfBasicInformation getFields() {
        LOG.info("Executing operation getFields");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getCountries()*
     */
    public ArrayOfBasicInformation getCountries() {
        LOG.info("Executing operation getCountries");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getMaritalStatuses()*
     */
    public ArrayOfBasicInformation getMaritalStatuses() {
        LOG.info("Executing operation getMaritalStatuses");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getGenders()*
     */
    public ArrayOfBasicInformation getGenders() {
        LOG.info("Executing operation getGenders");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getIdentificationDocumentTypes()*
     */
    public ArrayOfBasicInformation getIdentificationDocumentTypes() {
        LOG.info("Executing operation getIdentificationDocumentTypes");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getQuestions()*
     */
    public ArrayOfBasicInformation getQuestions() {
        LOG.info("Executing operation getQuestions");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getPoliticalRepresentationTypes()*
     */
    public ArrayOfBasicInformation getPoliticalRepresentationTypes() {
        LOG.info("Executing operation getPoliticalRepresentationTypes");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring.camel.test1.dto.wsdl.basicinformation.IBasicInformationQueryService#getResponsesResponses()*
     */
    public ArrayOfBasicInformation getResponsesResponses() {
        LOG.info("Executing operation getResponsesResponses");
        try {
            ArrayOfBasicInformation _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
